name: RL_project
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.1.0
  - numpy
  - python=3.6
  - scipy=1.3.0
  - seaborn=0.9.0
  - tqdm=4.32.1
  - pytorch=1.6.0
  - torchvision=0.7.0
  - pyglet=1.3.2
  - flask=1.1.2
  - flask-socketio=4.3.1
  - pip=19.3
  - Werkzeug==1.0.0
  - swig
  - pip:
    - gym
    - box2d-py
